import type { NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/Home.module.css';
import ProductsClasses from 'styles/products.module.css';
import { useQuery, gql } from '@apollo/client';
import type { Products } from 'types';
import Product from 'components/Product';

const QUERY = gql`
  query Categories {
    category {
      name
      products {
        name
        id
        inStock
        gallery
        prices {
          currency {
            label
            symbol
          }
          amount
        }
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } =
    useQuery<{ category: { products: Products } }>(QUERY);
  console.log(data);
  if (loading) return <h1>loadinggg</h1>;
  if (error) return <h1>{error.toString()}</h1>;
  console.log(data?.category.products.length);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>Welcome to Swiftx store</h1>
        <div className={ProductsClasses.products}>
          {data?.category.products.map((pr) => (
            <Product product={pr} key={pr.id} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
